name: Sync Fork

on:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
      with:
        upstream_repository: shwang1114/InjectLib
        target_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
